### ISSUE TITLE
Local/app JS module files in importmap

### ISSUE THREAD

**Issue by heyman** [dropseed/django-importmap#16]
I want to add application specific entries to the importmap (e.g. `static/some/file.js` in development and `{{ STATIC_URL }}some/file-[hash].js` in production) and not only jspm.io libraries. Since browsers seems to only support a single importmap, I believe I have to inject my entries into the importmap JSON data generated by django-importmap before rendering it in a template.

Is there any plan/interest in having django-importmap support local files? If not, maybe there should be a documented way to extend the importmap?

I believe [importmap-rails](https://github.com/rails/importmap-rails/#selectively-importing-modules) has support for something like this (though I guess Rails is less "frontend agnostic" than Django, so it might be hard to come up with a good general solution).

**Comment by davegaeddert** [comment]
Not sure I have time to actually test this today, but something like this? https://github.com/dropseed/django-importmap/pull/17/files#diff-a16e2559640affd911f867e536059380fb04503fe549594e54a50f671c32aa56R13

**Comment by heyman** [comment]
Yes :+1:, something like that looks good!

**Comment by davegaeddert** [comment]
Let's just go with it! I was trying to think how it would work in `importmap.toml`, but I'm not actually sure there's any advantage to trying to do it there (at least not right now). This is pretty easy to reason about.

**Comment by davegaeddert** [comment]
This and the Jinja stuff are now in v0.2.0 if you want to mess with it.

**Comment by heyman** [comment]
Great, I'll try this out tomorrow (it's 1 AM here).

I've just started to set up a new project, and my goal is to use importmaps through django-importmaps and not have to setup webpack at all (fingers crossed). Once the project setup has settled a bit more I can report back.

Thanks for very quick responses :)!
