### ISSUE TITLE
👍 cool project ⭐️

### ISSUE THREAD

**Issue by codingjoe** [dropseed/django-importmap#23]
Hi there 👋,

Just wanted to share some love ❤️
I wanted to upgrade to ESM loading in the browser instead of bundled development for a while now.
This is a great step towards such a future in the Django world.

Please let me know if you have a donation link. I'd love to support this project.
I'd also be happy to contribute. My main interest would be adding support for JS unit tests.

Thanks for working on such a project.

Cheers!
Joe

**Comment by davegaeddert** [comment]
Thanks @codingjoe! No need to donate right now, but I appreciate the offer.

I'd be happy to look at some contributions. Not sure I'm following what JS unit tests would be, but feel free to tell me more!

**Comment by codingjoe** [comment]
I was considering supporting a setup that makes files accessible locally to run a test runner like Jest. Let's say you write a lit component and do a sweet little `import 'lit'`. Your browser has the import mapping, when running Jest on your local machine, or on CI, the running wouldn't know how to resolve the import.

I figured, since testability is part of Django's success, that'd be a nice thing to continue and carry into the JavaScript part of your application.
